# Generated by Django 3.2.7 on 2021-09-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0002_rename_ratings_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
