# Generated by Django 3.2.7 on 2021-09-18 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0003_remove_profile_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rateApp.project'),
        ),
    ]
