# Generated by Django 3.2.7 on 2021-09-23 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0006_auto_20210919_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
