# Generated by Django 3.2.7 on 2021-09-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0007_project_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rateApp.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_rated', to='rateApp.rating'),
            preserve_default=False,
        ),
    ]
