# Generated by Django 3.2.7 on 2021-09-23 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0009_remove_project_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='project',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_rated', to='rateApp.project'),
            preserve_default=False,
        ),
    ]
