# Generated by Django 3.2.7 on 2021-09-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateApp', '0012_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='screenshot',
            new_name='image',
        ),
    ]
